name: pkgdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: |
            ~/R/Library
            ~/.R/pkgdown
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R dependencies
        run: |
          R -e "install.packages('remotes')"
          R -e "remotes::install_cran(c('pkgdown', 'shiny', 'ggplot2', 'dplyr', 'DT', 'tidyr', 'scales', 'yaml', 'knitr', 'rmarkdown'))"
          R -e "remotes::install_deps(dependencies = TRUE)"

      - name: Build pkgdown site
        run: |
          R -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
